###
get http://localhost:4000/user

###
post http://localhost:4000/user/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "red@gmail.com",
    "password": "123456",
    "contact": "9999888880"
}

###
post http://localhost:4000/user/login
Content-Type: application/json

{
    "email": "red@gmail.com",
    "password": "123456"
}

###
delete http://localhost:4000/user/67a8867e266dcca53442ff28